# Generated by Django 4.2.30 on 2026-09-28 16:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True, verbose_name='N° Orden')),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='Cliente')),
                ('cliente_telefono', models.CharField(max_length=50, verbose_name='Teléfono / WhatsApp')),
                ('moto_modelo', models.CharField(max_length=120, verbose_name='Vehículo / Modelo')),
                ('moto_placa', models.CharField(max_length=30, verbose_name='Chapa / Placa')),
                ('moto_kilometraje', models.IntegerField(blank=True, null=True, verbose_name='Kilometraje')),
                ('estado', models.CharField(choices=[('banco', 'En Banco'), ('repuesto', 'Espera Repuesto'), ('listo', 'Listo Retiro'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='banco', max_length=20)),
                ('nivel_combustible', models.CharField(choices=[('reserva', 'Reserva / Bajo'), ('1_4', '1/4 Tanque'), ('1_2', '1/2 Tanque'), ('3_4', '3/4 Tanque'), ('lleno', 'Tanque Lleno')], default='1_2', max_length=20)),
                ('fecha_promesa', models.DateField(blank=True, null=True, verbose_name='Promesa de Entrega')),
                ('motivo_ingreso', models.TextField(verbose_name='Motivo de Ingreso')),
                ('observaciones_vehiculo', models.TextField(blank=True, null=True, verbose_name='Detalle / Observaciones')),
                ('total_presupuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Mecánico')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('repuesto', 'Repuesto / Insumo'), ('servicio', 'Mano de Obra')], default='repuesto', max_length=20)),
                ('concepto_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tipo_iva', models.IntegerField(default=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.articulo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicios.ordentrabajo')),
            ],
        ),
    ]
