# Generated by Django 4.2.30 on 2026-09-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='nivel_combustible',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='deposito_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='compras.deposito', verbose_name='Depósito Salida'),
        ),
    ]
