# Generated by Django 4.2.30 on 2026-09-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('servicios', '0002_remove_ordentrabajo_nivel_combustible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='tipo_iva',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.deposito'),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='tipo',
            field=models.CharField(choices=[('repuesto', 'Repuesto / Insumo'), ('producto', 'Producto'), ('servicio', 'Mano de Obra')], default='repuesto', max_length=20),
        ),
    ]
