# Generated by Django 4.2.30 on 2026-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_remove_detalleorden_tipo_iva_detalleorden_deposito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre & Apellido')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono / WhatsApp')),
                ('moto_modelo', models.CharField(blank=True, max_length=120, null=True, verbose_name='Vehículo / Modelo habitual')),
                ('moto_placa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Chapa / Matrícula')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente Recurrente',
                'verbose_name_plural': 'Clientes Recurrentes',
                'ordering': ['nombre'],
            },
        ),
    ]
