# Generated by Django 4.2.30 on 2026-09-27 22:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('presentacion', models.CharField(blank=True, max_length=80, null=True)),
                ('costo_referencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=30, unique=True)),
                ('timbrado', models.CharField(blank=True, max_length=8, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(editable=False, max_length=20, unique=True)),
                ('timbrado', models.CharField(max_length=8)),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('recibo', 'Recibo / Boleta Interna'), ('remision', 'Nota de Remisión'), ('importacion', 'Despacho / Importación'), ('credito', 'Nota de Crédito')], default='factura', max_length=20)),
                ('numero_comprobante', models.CharField(max_length=50)),
                ('fecha_comprobante', models.DateField()),
                ('condicion', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=15)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('moneda', models.CharField(choices=[('PYG', 'PYG (Gs.)'), ('USD', 'USD ($)'), ('BRL', 'BRL (R$)'), ('ARS', 'ARS ($)'), ('EUR', 'EUR (€)')], default='PYG', max_length=5)),
                ('cotizacion', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('comprobante_adjunto', models.FileField(blank=True, null=True, upload_to='comprobantes_compras/%Y/%m/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('total_exentas', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('total_iva5', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('total_iva10', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('liquidacion_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('total_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('fecha_insercion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('anulado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_creados', to=settings.AUTH_USER_MODEL)),
                ('deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='compras.deposito')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_modificados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='compras.proveedor')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_proveedor', models.CharField(blank=True, max_length=60, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('iva_porcentaje', models.IntegerField(choices=[(0, 'Exenta'), (5, 'IVA 5%'), (10, 'IVA 10%')], default=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='compras.articulo')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='compras.articulo')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='compras.deposito')),
            ],
            options={
                'unique_together': {('articulo', 'deposito')},
            },
        ),
    ]
