# Generated by Django 4.2.30 on 2026-09-29 16:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transferencia', models.CharField(max_length=30, unique=True, verbose_name='N° Transferencia')),
                ('fecha', models.DateField(verbose_name='Fecha Transferencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Motivo / Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='compras.deposito')),
                ('deposito_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='compras.deposito')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_transferencia', to='compras.articulo')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.transferencia')),
            ],
        ),
    ]
