"""
Django settings for rfasys project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bq8h$=#*$b6^z%_=^c**%i8)dv^fwpx20)&*!^x46xz8t2fh_+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

import os
import getpass
# Detecta si corre en PythonAnywhere por usuario o ruta (sin importar mayúsculas)
EN_PRODUCCION = getpass.getuser().lower() == 'rfaytsys' or 'rfaytsys' in str(BASE_DIR).lower()

# Application definition

INSTALLED_APPS = [
    *(['baton'] if EN_PRODUCCION else []),
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps locales
    'home',
    'compras',
    'servicios',
    'ventas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rfasys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rfasys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# Desactivado para entorno de desarrollo local (permite claves como "123")
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-py'

TIME_ZONE = 'America/Asuncion'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Añade este bloque para indicarle a Django dónde buscar la carpeta static raíz:
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# ESTA ES LA LÍNEA OBLIGATORIA QUE FALTA:
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_AGE = 600
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Redirige automáticamente al login raíz cuando la sesión expire o requiera autenticación
LOGIN_URL = 'inicio'

if EN_PRODUCCION:
    BATON = {
        'SITE_HEADER': 'RFA&T/SYS',
        'SITE_TITLE': 'RFA&T/SYS Admin',
        'INDEX_TITLE': 'Administración del Sistema',
        'SUPPORT_HREF': '#',
        'COPYRIGHT': 'copyright © 2026 RFA&T/SYS',
        'POWERED_BY': '<a href="#">RFA&T/SYS</a>',
        'CONFIRM_UNSAVED_CHANGES': True,
        'SHOW_MULTIPART_UPLOADING': True,
        'ENABLE_IMAGES_PREVIEW': True,
        'CHANGELIST_FILTERS_IN_MODAL': True,
        'CHANGELIST_FILTERS_ALWAYS_OPEN': False,
        'MENU_ALWAYS_COLLAPSED': False,
        'MENU_TITLE': 'Menú',
        'GRAVATAR_DEFAULT': 'retro',
    }

    # ==============================================================================
# SEGURIDAD Y PROTECCIÓN CSRF
# ==============================================================================

# Dominios autorizados para procesar peticiones POST en HTTPS (PythonAnywhere)
CSRF_TRUSTED_ORIGINS = [
    'https://rfaytsys.pythonanywhere.com',
]

# Permitir que el token CSRF viaje seguro y no se invalide por sesión
CSRF_COOKIE_SECURE = EN_PRODUCCION  # True en la nube (HTTPS), False en local (HTTP)
SESSION_COOKIE_SECURE = EN_PRODUCCION

# Evitar desincronizaciones de CSRF con las cookies de sesión
CSRF_COOKIE_HTTPONLY = False